name: smooth_mnist_binary

cpus: 10
max_time: "24:00:00"
memory_gb: 64
# What information should SLURM send about the job via email? (see docs)
mail_type: END
debug: True
gpus: 0

hyperparams_grid:
    - dataset.name: [mnist01]
    - dataset.samples_train: [10000]

    - model.name: shallow
    - model.hidden_size: [256]
    - model.epochs: 100
    - model.batch_size: 64
    - model.iteration: [0]
    - model.learning_rate: [0.01]
    - model.init_scale:    [1.0 ]
    - model.loss_threshold: 0
    - model.weights_product_reg_coef: 0
    - model.gradient_norm_reg_coef: 0 
    - model.pca_dims: [8, 32, 128, 512]
