name: gp_1d

cpus: 64
max_time: "48:00:00"
memory_gb: 64
# What information should SLURM send about the job via email? (see docs)
mail_type: END
debug: False
gpus: 0

hyperparams_grid:
    - dataset.name: gp
    - dataset.lengthscale: 0.5
    - dataset.seed: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    - dataset.noise_var: 0
    - dataset.samples_train: [2, 3, 4, 5, 6, 7, 8, 9, 10]
#    - dataset.samples_train: [2, 4, 8, 16, 32, 64, 128]

    - model.name: shallow
    - model.hidden_size: 256
    - model.epochs: 50000
    - model.batch_size: null # batch size is None => GD, not SGD
    - model.iteration: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    - model.learning_rate: [0.1]
    - model.init_scale:    [0.01 ]
    - model.error_threshold: 0.001
