name: smooth_gradient_reg

cpus: 20
max_time: "24:00:00"
memory_gb: 64
# What information should SLURM send about the job via email? (see docs)
mail_type: END
debug: False

hyperparams_grid:
    - dataset.name: mnistparity
#    - dataset.samples_train: [10, 17, 28, 46, 77, 129, 215, 359, 599, 1000]
    - dataset.samples_train: [10000]

    - model.name: shallow
    - model.hidden_size: [64]
    - model.epochs: 50000
    - model.batch_size: 64
    - model.iteration: [0]
    - model.learning_rate: [0.01]
    - model.init_scale:    [1.0]
    - model.loss_threshold: 0
    - model.weights_product_reg_coef: [0., 1.e-6, 1.e-5, 1.e-4, 1.e-3, 1.e-2]
#    - model.gradient_norm_reg_coef: [0., 1.e-6, 1.e-5, 1.e-4, 1.e-3]
